services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    container_name: mongodb
    restart: always
    ports:
      - "27020:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: |
        mongosh --eval "
        try {
          rs.status();
        } catch(e) {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongo:27017' }]
          });
        }
        " --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
    # volumes:
    #   - ./Data/mongo-data:/data/db
    #   - ./Data/mongo-config:/data/configdb
    networks:
      default:
        aliases:
          - mongo

  mongo-express:
    image: mongo-express:1.0.2-18
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/?replicaSet=rs0
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123
    depends_on:
      mongodb:
        condition: service_healthy
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly no
      --save ""
      --maxmemory 1gb
      --maxmemory-policy volatile-lru
    # volumes:
    #   - ./Data/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  # redis://default@redis:6379
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    restart: unless-stopped

networks:
  default:
    name: urlservice_net